Update ci.yml
because of issue: 
Run chmod +x ./gradlew build
chmod: cannot access 'build': No such file or directory
Error: Process completed with exit code 1.